// File: lib/episodesData.ts

export interface Episode {
  season: number;
  episode: number;
  title: string;
  date: string;
  host: string;
  guest: string;
  description: string;
  youtubeId: string;
  thumbnail: string;
  spotifyUrl: string;
  soundcloudUrl: string;
}

export const episodesData: Record<string, Episode> = {
  's2e13': {
    season: 2,
    episode: 13,
    title: 'Igniting Brands: John Heinz of Spark Branded Solutions on Powering the Promo Industry',
    date: 'October 13, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'John Heinz',
    description: 'Creativity and strategy ignite brands in the promotional products industry.',
    youtubeId: 'FiuFHvjiQG0',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/6YJwxblHuVrKggvUPrAjb8',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e12': {
    season: 2,
    episode: 12,
    title: 'Investing in Impact: Brandily\'s Take on Promotional Spend',
    date: 'October 3, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Sarah Lilley',
    description: 'Impact-driven promotional investments that maximize ROI and visibility.',
    youtubeId: '6rNuDGxOPa0',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/6ztqXWZme3PLpnlSn010co',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e11': {
    season: 2,
    episode: 11,
    title: 'Inside Fully Promoted: Franchise Strategies That Work',
    date: 'October 1, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Tyler Sherwood',
    description: 'Franchise growth tactics, brand identity, and scaling across markets.',
    youtubeId: 'Tui8JvGRu1s',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/3Cg9639IK3I5sjz55vJQXi',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e10': {
    season: 2,
    episode: 10,
    title: 'Elevating Brands with Custom Gifts',
    date: 'September 19, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Rich Patterson',
    description: 'Creating elevated, engaging, cherished products with PBJ Merch Co.',
    youtubeId: '2K0k2sKKctg',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/472Eql12Nm1T6Gu5s5h51b',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e9': {
    season: 2,
    episode: 9,
    title: 'Lane Seven\'s Blueprint: Smarter Branding Strategies from Alyssa Inkrott',
    date: 'September 15, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Alyssa Inkrott',
    description: 'Apparel storytelling and smarter brand identity strategies.',
    youtubeId: 'xYSjdO1JseM',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/0negmIBGNanbqqprZJn6vR',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e8': {
    season: 2,
    episode: 8,
    title: 'Inside the Promo Industry: Colin Loughran of Five Fisherwick',
    date: 'September 10, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Colin Loughran',
    description: 'Innovative branding strategies and the future of promo.',
    youtubeId: 'RcWiQ1K1Xv4',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/5hLMGcpRZFao2GUDJbpQbN',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e7': {
    season: 2,
    episode: 7,
    title: 'Bottled Up Branding: The Power of Promotional Drinkware',
    date: 'September 3, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Priscila Angus',
    description: 'Premium drinkware, eco-conscious design, and impactful branding.',
    youtubeId: 'hnX39oC7EgE',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/0xPGqrkASpbVeVlxPvuHDo',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e6': {
    season: 2,
    episode: 6,
    title: 'Blankets That Speak Louder Than Logos',
    date: 'August 22, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Jenny Barcus',
    description: 'Premium woven throws tell stories far beyond a logo.',
    youtubeId: 'DqGKz5rp3vY',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/0WecLWisiszpwaThuCuZXf',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e5': {
    season: 2,
    episode: 5,
    title: 'From Logo to Legacy: Turning Promotional Products into Brand Experiences',
    date: 'August 14, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Megh Chahl',
    description: 'Branded merchandise for awareness, relationships, and lasting impressions.',
    youtubeId: 'itrNqSBR_As',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/5s7bz6X2OO4nRfiA0JxZ6W',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e4': {
    season: 2,
    episode: 4,
    title: 'The Future of Brand Loyalty Starts with Gen-Z',
    date: 'August 2, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Caden Knebel',
    description: 'Etchify, loyalty, and engagement through a Gen-Z lens.',
    youtubeId: '5NqO-9-Olig',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/5IArWibnxknltjRgmbDibP',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e3': {
    season: 2,
    episode: 3,
    title: 'Promotional Products Reimagined: Smart Strategies for Maximum Brand Impact',
    date: 'July 29, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Riley Friar',
    description: 'Trends, pitfalls, and strategy behind merchandise campaigns.',
    youtubeId: 'SHcwa1h5mYs',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/7E48ToZVlOLR3PyVbYhoB5',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e2': {
    season: 2,
    episode: 2,
    title: 'B2B vs B2C – Lessons in Leadership from Both Sides',
    date: 'June 26, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Nicole Stachowicz',
    description: 'Contrasting strategies, communication, and decision-making.',
    youtubeId: 'xxVedKJx3b4',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/show/7A7v0AR7Bcf7wAVGbvlMmm',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's2e1': {
    season: 2,
    episode: 1,
    title: 'Beyond the Logo: Building Brand Loyalty Through Promo Solutions',
    date: 'June 20, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'Samantha Fullerton',
    description: 'Promo solutions shaping lasting brand loyalty.',
    youtubeId: 'PbIIXGSwtUI',
    thumbnail: 'assets/img/pages/Podcast/Vectorart-podcast logo.jpg',
    spotifyUrl: 'https://open.spotify.com/show/7A7v0AR7Bcf7wAVGbvlMmm',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476',
  },
  's1e12': {
    season: 1,
    episode: 12,
    title: 'Headwear with Purpose: Designing Promo that Tells a Story',
    date: 'April 25, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'FEDERICO PASINI',
    description: 'Purpose‑driven, sustainable headwear and ethical production.',
    youtubeId: 'TCsqYEzMlZE',
    thumbnail: 'assets/img/pages/Podcast/16.jpeg',
    spotifyUrl: 'https://open.spotify.com/episode/5Z0txAJOubNAWAP7bZxlYM',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/episode-12-headwear-with',
  },
  's1e11': {
    season: 1,
    episode: 11,
    title: 'The Anatomy of a Perfect Cap: Exploring Premium Fabrics & Designs',
    date: 'April 23, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'MAX LEONARD',
    description: 'American twill, brushed cotton, mesh backs, and poly twill.',
    youtubeId: 'lEzV3lI5bOg',
    thumbnail: 'assets/img/pages/Podcast/15.jpeg',
    spotifyUrl: 'https://open.spotify.com/episode/6NsYYSCkXqFx26KE3omO5a',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/episode-11-the-anatomy-of-a-perfect-cap-exploring-premium-fabrics-designs',
  },
  's1e10': {
    season: 1,
    episode: 10,
    title: 'The latest trends and innovations in sustainable promotional products',
    date: 'April 22, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'JESYCA HOPE',
    description: 'Recycled materials, bamboo, organic cotton, reusable items.',
    youtubeId: 'Q1rpr0jXUdE',
    thumbnail: 'assets/img/pages/Podcast/14.jpeg',
    spotifyUrl: 'https://open.spotify.com/episode/4zjAbeWV9NIXPTbqtV4JiZ',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/episode-10-eco-friendly-swag',
  },
  's1e9': {
    season: 1,
    episode: 9,
    title: 'The Do\'s & Don\'ts of Rebranding with Promotional Products',
    date: 'April 9, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'GLORIA LAFONT',
    description: 'Aligned products, consistent messaging, tracking engagement.',
    youtubeId: '-t55-xYCBIE',
    thumbnail: 'assets/img/pages/Podcast/13.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/7D28MllJtpoGk6l47z2tlC',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/b068232b-99d2-4395-b24b-c91ac169e6a1',
  },
  's1e8': {
    season: 1,
    episode: 8,
    title: 'AI & Personalization in Promotional Products: The Next Big Thing',
    date: 'April 4, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'CAT GAGLIARDO',
    description: 'AI-driven personalization, engagement, privacy balance.',
    youtubeId: 'O9vfceusZ8g',
    thumbnail: 'assets/img/pages/Podcast/12.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/04xelmKHhy7HxOKVFcQkaT',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/episode-8-ai-is-taking-over-your-swag-bag',
  },
  's1e7': {
    season: 1,
    episode: 7,
    title: 'The Psychology of Freebies: Why Customers Love Branded Giveaways',
    date: 'April 3, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'ALEX BRADLEY',
    description: 'Triggers that drive loyalty, trust, engagement, and ROI.',
    youtubeId: 'VmPboRkFRHk',
    thumbnail: 'assets/img/pages/Podcast/12.jpeg',
    spotifyUrl: 'https://open.spotify.com/episode/7cdGJ5MaJZIxixYzcaVKV7',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/episode-7-the-psychology-of-freebies-why-customers-love-branded-giveaways',
  },
  's1e6': {
    season: 1,
    episode: 6,
    title: 'From Swag to Sales: How Promotional Items Can Drive Business Growth',
    date: 'April 2, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'HILLARY SCALETTA',
    description: 'Recognition, loyalty, integration into strategy.',
    youtubeId: 'YSz0XHeTB0A',
    thumbnail: 'assets/img/pages/Podcast/11.png',
    spotifyUrl: 'https://open.spotify.com/episode/04eNuwPLFR7aKlQQ2wwhlW',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/from-swag-to-sales-how-promotional-items-can-drive-business-growth',
  },
  's1e5': {
    season: 1,
    episode: 5,
    title: 'Stand Out & Scale Up: The Role of Promotional Products in Small Business Success',
    date: 'March 18, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'ROSS GREENSTEIN',
    description: 'Visibility, engagement, referrals, and growth.',
    youtubeId: 'B3MtldUMudI',
    thumbnail: 'assets/img/pages/Podcast/10.jpg',
    spotifyUrl: 'https://open.spotify.com/episode/1WwHMewWvZrE1lzl0KBc1e',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/are-you-using-promotional-products-the-right-way-find-out-in-episode-5',
  },
  's1e4': {
    season: 1,
    episode: 4,
    title: 'Promotional product: A key Part of America\'s Gifting Culture',
    date: 'March 13, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'KRISTINA BEAL',
    description: 'Tradition, impressions, and connections.',
    youtubeId: '76Gh2-38KwE',
    thumbnail: 'assets/img/pages/Podcast/9.png',
    spotifyUrl: 'https://open.spotify.com/episode/3JJMojejNl2PJMksWIuZCx',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/promotional-products-a-key-part-of-americas-gifting-culture',
  },
  's1e3': {
    season: 1,
    episode: 3,
    title: 'Nurturing the Next Generation: Wisdom from a 4-Decade Career',
    date: 'February 26, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'THE UNCLE EARL',
    description: 'Mentoring, leadership, resilience, adaptability.',
    youtubeId: 'agvnQCvBmqA',
    thumbnail: 'assets/img/pages/Podcast/7.png',
    spotifyUrl: 'https://open.spotify.com/episode/0HSYohA3j58oGLe9ORbsVp',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/nurturing-the-next-generation-wisdom-from-a-4-decade-career',
  },
  's1e2': {
    season: 1,
    episode: 2,
    title: 'Top Promotional Products Distributors & Suppliers in the USA',
    date: 'February 15, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'CASSANDRA CHIODO',
    description: 'Leading companies for branded merchandise and giveaways.',
    youtubeId: 'E0pGLiFeqqg',
    thumbnail: 'assets/img/pages/Podcast/6.png',
    spotifyUrl: 'https://open.spotify.com/episode/7aJzarDrJUjgr4DH8Dh6PY',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/dive-into-an-insightful-session-with-a-leading-promotional-products-distributor-and-supplier-in-the-usa',
  },
  's1e1': {
    season: 1,
    episode: 1,
    title: 'Unlocking Growth: The $26 Billion Promotional Products Industry',
    date: 'January 15, 2025',
    host: 'ROHIT JAISWAL',
    guest: 'JESSICA VAN METER',
    description: 'Trends, strategies, and opportunities in promo.',
    youtubeId: '4_OQkH9OJSo',
    thumbnail: 'assets/img/pages/Podcast/3.png',
    spotifyUrl: 'https://open.spotify.com/episode/2T3f76HrOZ7RzecPMrwMXZ',
    soundcloudUrl: 'https://soundcloud.com/rohit-jaiswal-518225476/unlocking-the-potential-of-the',
  },
};

export function getAllEpisodes(): Episode[] {
  return Object.values(episodesData);
}

export function getEpisodesBySeason(season: number): Episode[] {
  return getAllEpisodes().filter(ep => ep.season === season);
}

export function getEpisodeById(id: string): Episode | undefined {
  return episodesData[id];
}